apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-dev
  namespace: ns-dev
spec:
  selector:
    matchLabels:
      app: dept-dev
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dept-dev
    spec:
      containers:
      - name: dept-dev
        image: public.ecr.aws/h3u1y5t3/ecr:number
        ports:
        - containerPort: 80
